In [1]:
import numpy as np
import matplotlib.pyplot as plt
import contact_utils as cu

In [2]:
cmap = cu.ContactMapWrapperTri(2)

In [9]:
cmap.get_one_face_coeff(0, 1)

1

In [3]:
test_int_mat = cmap.get_single_species_contact_matrix(0)

In [8]:
test_int_mat += 1

In [9]:
test_int_mat

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
cmap.set_single_species_contact(0, test_int_mat)

In [20]:
cmap.contact_map

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
test_int_mat = cmap.get_single_species_contact_matrix(0)

In [19]:
test_int_mat += 2

In [15]:
test_int_mat

array([[3., 3., 3., 3., 2., 2.],
       [3., 3., 3., 3., 2., 2.],
       [3., 3., 3., 2., 2., 2.],
       [3., 3., 3., 2., 2., 2.],
       [3., 3., 2., 2., 2., 2.],
       [3., 3., 2., 2., 2., 2.]])

In [14]:
cmap.set_single_species_contact(1, test_int_mat)

Contact energies are not symmetric! Aborting


In [16]:
cmap.get_interaction_coeff(0, 1, 0, 1)

0